var SafeMath = artifacts.require('.openzeppelin-solidity/contracts/math/SafeMath.sol');
var AEToken = artifacts.require("./TestToken.sol");
var BATToken = artifacts.require("./TestToken.sol");
var BNBToken = artifacts.require("./TestToken.sol");
var BNTToken = artifacts.require("./TestToken.sol");
var BTMToken = artifacts.require("./TestToken.sol");
var EOSToken = artifacts.require("./TestToken.sol");
var GNTToken = artifacts.require("./TestToken.sol");
var ICXToken = artifacts.require("./TestToken.sol");
var OMGToken = artifacts.require("./TestToken.sol");
var PLRToken = artifacts.require("./TestToken.sol");
var PPTToken = artifacts.require("./TestToken.sol");
var QTUMToken = artifacts.require("./TestToken.sol");
var REPToken = artifacts.require("./TestToken.sol");
var SALTToken = artifacts.require("./TestToken.sol");
var SNTToken = artifacts.require("./TestToken.sol");
var TRXToken = artifacts.require("./TestToken.sol");
var VENToken = artifacts.require("./TestToken.sol");
var ZILToken = artifacts.require("./TestToken.sol");
var ZRXToken = artifacts.require("./TestToken.sol");
var CVCToken = artifacts.require("./TestToken.sol");
var STORJToken = artifacts.require("./TestToken.sol");
var RDNToken = artifacts.require("./TestToken.sol");
var REQToken = artifacts.require("./TestToken.sol");
var POEToken = artifacts.require("./TestToken.sol");
var EDGToken = artifacts.require("./TestToken.sol");
var DNTToken = artifacts.require("./TestToken.sol");
var HTToken = artifacts.require("./TestToken.sol");
var VERIToken = artifacts.require("./TestToken.sol");
var KNCToken = artifacts.require("./TestToken.sol");
var FUNToken = artifacts.require("./TestToken.sol");

module.exports = function(deployer) {
  deployer.deploy(SafeMath);
  deployer.link(SafeMath,AEToken);
  deployer.link(SafeMath,BATToken);
    deployer.link(SafeMath,BNTToken);
    deployer.link(SafeMath,BTMToken);
    deployer.link(SafeMath,EOSToken);
    deployer.link(SafeMath,GNTToken);
    deployer.link(SafeMath,ICXToken);
    deployer.link(SafeMath,OMGToken);
    deployer.link(SafeMath,PLRToken);
    deployer.link(SafeMath,PPTToken);
    deployer.link(SafeMath,QTUMToken);
    deployer.link(SafeMath,REPToken);
    deployer.link(SafeMath,SALTToken);
    deployer.link(SafeMath,SNTToken);
    deployer.link(SafeMath,TRXToken);
    deployer.link(SafeMath,VENToken);
    deployer.link(SafeMath,ZILToken);
    deployer.link(SafeMath,ZRXToken);
    deployer.link(SafeMath,CVCToken);
    deployer.link(SafeMath,STORJToken);
    deployer.link(SafeMath,RDNToken);
    deployer.link(SafeMath,REQToken);
    deployer.link(SafeMath,POEToken);
    deployer.link(SafeMath,EDGToken);
    deployer.link(SafeMath,DNTToken);
    deployer.link(SafeMath,HTToken);
    deployer.link(SafeMath,VERIToken);
    deployer.link(SafeMath,KNCToken);
    deployer.link(SafeMath,FUNToken);
  deployer.deploy(AEToken,'AE','18','273685830');
  deployer.deploy(BATToken,'BAT','18','1500000000');
  deployer.deploy(BNBToken,'BNB','18','194972068');
  deployer.deploy(BNTToken,'BNT','18','75671910');
  deployer.deploy(BTMToken,'BTM','8','1407000000');
  deployer.deploy(EOSToken,'EOS','18','1000000000');
  deployer.deploy(GNTToken,'GNT','18','1000000000');
  deployer.deploy(ICXToken,'ICX','18','400228739');
  deployer.deploy(OMGToken,'OMG','18','140245398');
  deployer.deploy(PLRToken,'PLR','18','800000000');
  deployer.deploy(PPTToken,'PPT','8','53252246');
  deployer.deploy(QTUMToken,'QTUM','18','100000000');
  deployer.deploy(REPToken,'REP','18','11000000');
  deployer.deploy(SALTToken,'SALT','8','120000000');
  deployer.deploy(SNTToken,'SNT','18','6804870');
  deployer.deploy(TRXToken,'TRX','6','100000000000');
  deployer.deploy(VENToken,'VEN','18','1000000000');
  deployer.deploy(ZILToken,'ZIL','12','12600000000');
  deployer.deploy(ZRXToken,'ZRX','18','1000000000');
  deployer.deploy(CVCToken,'CVC','8','1000000000');
  deployer.deploy(STORJToken,'STORJ','8','424999998');
  deployer.deploy(RDNToken,'RDN','18','99999999');
  deployer.deploy(REQToken,'REQ','18','999991396');
  deployer.deploy(POEToken,'POE','8','3141592653');
  deployer.deploy(EDGToken,'EDG','0','132046997');
  deployer.deploy(DNTToken,'DNT','18','1000000000');
  deployer.deploy(HTToken,'HT','18','500000000');
  deployer.deploy(VERIToken,'VERI','18','100000000');
  deployer.deploy(KNCToken,'KNC','18','215604424');
  deployer.deploy(FUNToken,'FUN','8','10999873621');
};